### ISSUE TITLE
Can we build a 32-bit version?

### ISSUE THREAD

**Issue by ajdawson** [conda-forge/eofs-feedstock#1]
I currently maintain builds of this package in my own channel, which includes a 32-bit Linux package which was specifically requested by a user. Can conda-forge build 32-bit packages? I ended up building mine on a 64-bit machine, just running the 32-bit version of miniconda. Any feedback appreciated @pelson, @ocefpaf.

**Comment by pelson** [comment]
Currently - no unfortunately. The cost of building the whole stack on conda-forge for linux-32 is relatively large (time cost) and I have been surprised that we haven't had a request for them so far. If we weren't to build linux-32 on conda-forge, is there anything we can do to make that easier to achieve from the feedstock in a non-automated fashion etc.?

**Comment by ajdawson** [comment]
Well, what I want is to be able to tell my users to use the conda-forge channel, but I know a lot of them use 32-bit Linux (unavoidable, it is what their institution provides them with) and this will leave them out. I don't want to have to tell one set of users to use one channel and the rest to use another, and I don't want to leave out anyone currently using packages from my channel.

I can easily build the Linux 32 packages from the feedstock recipes myself, but is there a way to upload to the conda-forge channel in a more manual way?

**Comment by pelson** [comment]
> I know a lot of them use 32-bit Linux (unavoidable, it is what their institution provides them with)

Ouch.

> I can easily build the Linux 32 packages from the feedstock recipes myself, but is there a way to upload to the conda-forge channel in a more manual way?

That is completely possible. Obviously the full stack wouldn't be available form conda-forge though (that would be from `defaults`). Would you just drop onto a linux-32 machine and build, or do you have some clever docker goodness? I'm trying to judge if we should make linux-32 an opt-in thing for conda-smithy or not.

**Comment by ocefpaf** [comment]
@pelson I never had a special request for Linux 32 when maintaining the IOOS channel, but the downloads (of some really old binaries I uploaded with tour old docker image BTW) kept increasing with time!

I have to confess that was a a little bit scary. I felt like I was leaving some people behind.

**Comment by ajdawson** [comment]
> Would you just drop onto a linux-32 machine and build, or do you have some clever docker goodness?

No cleverness in my current setup! I just have the 32-bit support libraries installed on my work desktop (Ubuntu 14.04 64-bit) and I installed the 32-bit miniconda on there. I just set up my path to point at the 32-bit version and build using that. I'm sure this could be replicated in a docker image easily enough.

A 32-bit opt-in would be nice I think, but it shouldn't be a burden. eofs is a pure Python package, and for pure Python packages, it feels like even this is overkill. I don't know what the difference between the resulting 32-bit and 64-bit packages would be if any. It would be nice if we could build a universal package for pure Python packages (if such a concept exists, I don't know).

I honestly wish we could just go with 64-bit and hope we don't miss out anyone, but for eofs the last support request relating to 32-bit packaging was last month... I think there may be a larger number of 32-bit users out there than we would like to imagine.

Having said all that, I think it might be best to keep this on the back-burner and see what happens. If I change the documentation of my packages to suggest conda-forge for installation it may well be only the odd person who has an issue if any, and they can perhaps be solved on a more personal basis rather than making hefty changes to conda-forge. However, if other conda-forge packages start to have the same requests then maybe that is something to look at more seriously.

**Comment by pelson** [comment]
>  It would be nice if we could build a universal package for pure Python packages (if such a concept exists, I don't know)

Yes, no-arch conda packages exist. We have had some issues with them (and testing them!), but may be something we can revisit.

Your suggestions sounds very sensible, we can course-correct if it does become a bigger issue.

Thanks @ajdawson.

**Comment by jakirkham** [comment]
As an update, there is some discussion of adding support for noarch Python packages in issue ( https://github.com/conda-forge/conda-smithy/issues/485 ), which may alleviate the underlying issue here.
